services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:latest
    volumes:
      - ./open-webui:/app/backend/data
    ports:
      - "3000:8080"
    depends_on:
      - ollama
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - open-webui